SGLang.lang = $.extend(SGLang.lang,{
    ToolTitle:      "SkylineGlobe - Skyline Software Systems, Inc.",
    ToolName:       "Viewshed Query",

    Text6:          "meter",
    Text7:          "Calculated",
    Text8:          "Add Point",
    Text9:          "Spacing",
    Text10:         "m. Above Ground",
    Text11:         "Target Altitude",
    Text12:         "Second Altitude",
    Text14:         "Color Scheme",
    Text15:         "Red|Green",
    Text16:         "Green",
    Text17:         "This operation may take few minutes. To abort click on the Close or the Back button on the tool's caption.",
    Text18:         "Generating elevation buffer.",
    Text19:         "Calculating query points.",
    Text22:         "Generating depth map.",
    Text26:         "Cannot generate viewshed query.",
    Text27:         "Point",
    Text28:         "Viewer Altitude",
    Text29:         "Roof Altitude",
    Text31:         "Calculating line of sight to points",
    Text32:         "Set Viewer Altitude",
    Text33:         "Above Model (m)",
    Text34:         "Saving points",
    Text38:         "Calculate",
    Text39:         "Viewshed Query analysis completed.",
    Text40:         "Query points created :",
    Text41:         "Close",
    Text42:         "Edit <br>Style",
    Text43:         "Visible",
    Text44:         "Not Visible",
    Text45:         "Partially Visible",
    Text46:         "Viewer",
    Text47:         "Red",
    TextAbort:      "(esc to abort)",


    Text999: ""
});