SGLang.lang = $.extend(SGLang.lang, {
  ToolTitle: "SkylineGlobe - Skyline Software Systems, Inc.",
  ToolName: "Embedded TerraExplorer Fusion",
  Header: "Embedded TerraExplorer Fusion Sample",
  SmallHeader: "This is a simple showcase of embedded TerraExplorer Fusion",
  AboutHeader: "Actions and tools can be exectuted from the web page.",
  ButtonLoadWithGUI: "With GUI",
  ButtonLoadWithoutGUI: "Without GUI",
  ButtonLoadPartialGUI: "Custom GUI",
  ButtonDistance: "Distance",
  ButtonArea: "Area",
  ButtonVolume: "Volume",
  ButtonProfile: "Profile",
  ButtonLayerComparison: "Compare",
  ButtonRotate: "Rotate",
  ButtonHome: "Home",
  ButtonDrawCircle: "Draw Circle",
  ButtonDrawArrow: "Draw Arrow",
  ButtonDrawBox: "Draw Box",
  CaptionGUI: "Load Fusion",
  CaptionTEFTools: "Tools",
  CaptionActions: "Actions",
  CaptionEvents: "Events",
});
